apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: "jenkins.192.168.1.99.nip.io"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: jenknis-jenkins
            port:
              number: 80
