name: CICD

on:
  push:
    branches: [ main ]
jobs:  
  run-k8d:
    name: Create k3d cluster and deploy application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: AbsaOSS/k3d-action@v2
        name: "Create single k3d Cluster with imported Registry"
        with:
          cluster-name: CICD-test-cluster
          args: >-
            --agents 3
            --no-lb
            --k3s-arg "--no-deploy=traefik,servicelb,metrics-server@server:*"
      - name: "Docker repo demo"
        run: |
          docker build . -t davarski/demo:v1.0.0
          k3d image import davarski/demo:v1.0.0 -c CICD-test-cluster --verbose
          kubectl run demo --image=demo:v1.0.0 --restart=Never

     
