# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
jobs:  
  run-k8d:
    name: Create k3d cluster
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: AbsaOSS/k3d-action@v2
        name: "Create single k3d Cluster with imported Registry"
        with:
          cluster-name: CI-test-cluster
          args: >-
            --agents 3
            --no-lb
            --k3s-arg "--no-deploy=traefik,servicelb,metrics-server@server:*"
      - name: "Docker repo demo"
        run: |
          docker build . -t davarski/demo:v1.0.0
          k3d image import davarski/demo:v1.0.0 -c CI-test-cluster --verbose
          kubectl apply -f pod.yaml

     pod.yaml
    
     apiVersion: v1
     kind: Pod
     metadata:
     name: test-pod
     spec:
       containers:
       - name: demo-app
         image: davarski/demo:v1.0.0 
